select datepart(yyyy,getdate())
select datepart(mm,getdate())
select datepart(dd,getdate())
select datepart(dw,getdate())
select datepart(hh,getdate())
select datepart(mi,getdate())
select datepart(ss,getdate())